### ISSUE TITLE
[Nexus] With vertical home menu: Pressing right arrow never take me to the power button

### ISSUE THREAD

**Issue by boirello** [MikeSiLVO/skin.transparency#4]
When you have vertical menu (not horizontal) at your home screen, you cannot navigate to the power button in top-right corner by pressing the right-arrow button on keyboard. But if you press left-arrow, you'll get there.

I've only tested with Kodi Nexus (20.2) on Ubuntu 22.04.

**Suggested resolution:**
In `skin.transparency/1080p/home.xml` add `<onright>` tag in line 42:
```xml
<control type="group" id="5050">
	<left>0</left>
	<top>0</top>
	<onright>20</onright><!-- Add this line -->
```

**Comment by MikeSiLVO** [comment]
Sorry but I see no reason to change this. 
One click left for power button makes more sense to me than numerous clicks past possible submenus and widgets.
